# Generated by Django 3.0.3 on 2020-03-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0003_auto_20200328_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feature_selection', models.CharField(choices=[('f_score', 'F-Score'), ('chi_square', 'Chi-Square'), ('cfs', 'Correlation-based Feature Selection')], default='', max_length=10)),
                ('reguralization', models.FloatField(default=1.0)),
                ('epsilon', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'predictions',
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.City')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicts.Prediction')),
            ],
            options={
                'db_table': 'prediction_results',
            },
        ),
    ]
