# Generated by Django 3.0.3 on 2020-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
