# Generated by Django 3.0.3 on 2020-03-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0002_auto_20200328_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='accuracy_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prediction',
            name='error_value',
            field=models.FloatField(default=0.0),
        ),
    ]
