# Generated by Django 3.0.3 on 2020-04-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0005_auto_20200408_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='reguralization',
            new_name='regularization',
        ),
    ]
