# Generated by Django 3.0.3 on 2020-06-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0008_prediction_default_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='accuracy_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='dumped_model',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='epsilon',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='error_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='feature_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='feature_selection',
            field=models.CharField(blank=True, choices=[('f_score', 'F-Score'), ('chi_square', 'Chi-Square'), ('cfs', 'Correlation-based Feature Selection')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='ranked_index',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='regularization',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
