# Generated by Django 3.0.3 on 2020-06-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0009_auto_20200615_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLearningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('feature_selection', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('accuracy_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('error_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('ranked_index', models.TextField(blank=True, default='', null=True)),
                ('feature_num', models.IntegerField(blank=True, default=0, null=True)),
                ('dumped_model', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'machine_learning_models',
            },
        ),
    ]
