# Generated by Django 3.0.3 on 2020-06-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0010_machinelearningmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='default_model',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='dumped_model',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='saved',
        ),
    ]
