# Generated by Django 3.0.3 on 2020-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0011_auto_20200615_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='epsilon',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='machinelearningmodel',
            name='regularization',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
