# Generated by Django 3.0.3 on 2020-06-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0013_prediction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
